const sentenceEnglishByTerm = {
  "企業文化": "This company's culture is very open.",
  "投資": "We are discussing new investment opportunities.",
  "投資人": "He is an investor in a technology company.",
  "收入": "This company's revenue increased this year.",
  "利潤": "We need to increase this product's profit.",
  "競爭": "This market is very competitive.",
  "市場": "The Taiwan market is very friendly to new brands.",
  "國際": "This is our first time attending an international trade show.",
  "政府": "The government recently released a new policy.",
  "政策": "This policy will affect many companies.",
  "內容": "This content is very suitable for social media.",
  "品牌": "This brand has been very popular recently.",
  "品牌合作": "I am responsible for brand partnerships and content planning.",
  "影片": "This video has very good traffic.",
  "觀眾": "We need to understand what the audience really wants to watch.",
  "流量": "This article brought in a lot of traffic.",
  "熱度": "This topic has a lot of buzz recently.",
  "推薦": "Can you recommend a good restaurant?",
  "熱賣": "This drink has been selling very well recently.",
  "限量版": "This is a limited edition, so it sold out quickly.",
  "體驗": "The user experience needs more optimization.",
  "高效": "This tool can help us complete the work efficiently.",
  "專業": "His presentation looks very professional.",
  "多功能": "This is a multifunctional editing tool.",
  "產品": "This product's positioning is very clear.",
  "簡報": "I need to make a presentation tomorrow.",
  "會議": "The afternoon meeting has been moved to three o'clock.",
  "團隊": "Our team is working on content planning.",
  "客戶": "This client wants to see the new proposal.",
  "方案": "Please send the proposal to the client.",
  "合作": "We hope to start collaborating next month.",
  "創作者": "This creator's videos are very creative.",
  "創意": "The creative idea for this ad is very fresh.",
  "創新": "The company needs more innovation.",
  "優化": "This feature still needs optimization.",
  "發展": "This industry is developing very quickly.",
  "結果": "The test results were better than expected.",
  "影響": "This change will affect the user experience.",
  "趨勢": "AI is a very important trend this year.",
  "數據分析": "We use data analysis to improve the content.",
  "工作內容": "Can you explain the job responsibilities?",
  "提到": "He mentioned the new strategy in the meeting.",
  "有效": "This method is very effective.",
  "年輕": "This brand is very popular with young people.",
  "年輕族群": "This event mainly attracts younger demographics.",
  "危險": "This intersection is a little dangerous.",
  "事件描述": "Please write a clear description of the event.",
  "原因": "We need to find the real reason.",
  "報告": "I need to finish this report before the meeting.",
  "報導": "This news report mentioned market trends.",
  "小吃": "The night market has a lot of tasty street food.",
  "小籠包": "This shop's soup dumplings are famous.",
  "滷肉飯": "I want to order a bowl of braised pork rice.",
  "牛肉麵": "Taiwanese beef noodle soup is very tasty.",
  "雞排": "The chicken cutlet at the night market is huge.",
  "豬肉": "There is pork in this dish.",
  "牛肉": "I prefer beef.",
  "雞肉": "This lunch box has chicken.",
  "鴨肉": "Duck soup is the signature dish here.",
  "羊肉": "Many people like eating lamb hot pot in winter.",
  "蛋": "Can you add an egg for me?",
  "海鮮": "The seafood at this restaurant is very fresh.",
  "什錦": "I ordered a bowl of assorted noodle soup.",
  "湯": "This bowl of soup is a little spicy.",
  "醬": "This sauce goes well with chicken cutlet.",
  "米糕": "Tainan sticky rice cake is famous.",
  "麻辣鍋": "We are going to eat spicy hot pot tonight.",
  "酸辣湯": "I want to order a bowl of hot and sour soup.",
  "蒸": "This dish is steamed.",
  "煮": "Beef noodle soup needs to cook for a longer time.",
  "炒": "I want to eat fried rice.",
  "烤": "This chicken is grilled.",
  "煎": "I eat a fried egg for breakfast.",
  "炸": "Chicken cutlet is usually deep-fried.",
  "滷": "This shop's braised snacks are very popular.",
  "飯": "I want to eat rice for lunch.",
  "麵": "This bowl of noodles tastes very good.",
  "粥": "Eating congee in the morning feels comforting.",
  "冰水": "Can you give me a glass of ice water?",
  "熱水": "I would like a cup of hot water.",
  "少冰": "I want less ice in my bubble tea.",
  "微冰": "Please make this drink with light ice.",
  "去冰": "I want no sugar and no ice.",
  "全糖": "This drink is full sugar, so it will be sweeter.",
  "半糖": "Please make the milk tea half sugar.",
  "微糖": "I usually drink light sugar.",
  "少糖": "Less sugar is fine for this drink.",
  "無糖": "I want unsweetened green tea.",
  "入口": "The MRT station entrance is ahead.",
  "出口": "Please exit from the exit on the right.",
  "電梯": "The elevator is on the left.",
  "樓": "The restaurant is on the second floor.",
  "路": "This road is very lively at night.",
  "街": "The night market is on that street.",
  "號": "The address is No. 10 Zhongshan Road.",
  "藥局": "Is there a pharmacy nearby?",
  "餐廳": "This restaurant requires a reservation.",
  "公司": "I need to go to the client's company today.",
  "捷運": "I take the MRT to the office every day.",
  "月臺": "The train is arriving soon, so please wait on the platform.",
  "列車": "This train is going toward Taipei.",
  "公車": "We can take the bus to the night market.",
  "巷": "This coffee shop is in a small alley.",
  "弄": "The address says Lane 3, No. 5.",
  "段": "The company is on Section 4 of Zhongxiao East Road.",
  "最近": "This brand has been very popular recently.",
  "年糕": "Many people eat rice cakes during Lunar New Year.",
  "燒賣": "The shumai at this Hong Kong-style restaurant is very good.",
  "點心": "We will eat a small snack in the afternoon.",
  "冰淇淋": "The weather is hot, and I want to eat ice cream.",
  "甜點": "We ordered dessert after the meal.",
  "客氣": "You're welcome. It is a small thing.",
  "對錯": "Do not rush to judge right and wrong.",
  "老闆娘": "The female shop owner recommended the signature dish to us.",
  "工作人員": "Excuse me, where is the staff entrance?",
  "按鈕": "Please press this button to confirm.",
  "宵夜": "After eleven tonight, we are going to eat a late-night meal.",
  "大樓": "The meeting room is in that building.",
  "公寓": "He lives in an apartment near the MRT station.",
  "酒店": "Our hotel is very close to the airport.",
  "商場": "There are many restaurants in the shopping mall.",
  "銀行": "The bank closes at 3:30 in the afternoon.",
  "醫院": "The hospital is next to the intersection.",
  "診所": "Is there a dentist clinic nearby?",
  "行銷": "She is responsible for brand marketing.",
  "影片製作": "We are doing video production recently.",
  "宣傳": "This event needs more promotion.",
  "資訊": "Please send me the event information.",
  "辣椒": "There are a lot of chili peppers in this sauce.",
  "青菜": "I want to order one more serving of greens.",
  "高麗菜": "There is cabbage in the dumplings.",
  "竹筍": "This bowl of soup has bamboo shoots.",
  "紅蘿蔔": "Carrots can make the soup sweeter.",
  "洋蔥": "There are onions in the beef rice.",
  "饅頭": "For breakfast, I eat steamed buns with soy milk.",
  "薯條": "Kids really like fries.",
  "中份": "I want one medium order of fries.",
  "鍋貼": "This shop's pan-fried dumplings are crispy.",
  "肉圓": "Changhua meatballs are famous.",
  "快炒": "Tonight we are going to a stir-fry restaurant.",
  "香菇": "This bowl of soup has shiitake mushrooms.",
  "醬油": "Pan-fried dumplings can be dipped in a little soy sauce.",
  "少鹽": "Can this dish be made with less salt?",
  "蔥油": "Scallion pancakes are a very common street food.",
  "糖醋排骨": "Sweet and sour pork ribs are sour and sweet.",
  "滿滿": "This bowl of noodles is packed with toppings.",
  "空": "Is this seat empty?",
  "停車": "You cannot park here.",
  "地下": "The parking lot is on basement level two.",
  "特價": "This product is on sale today.",
  "所有": "All the materials are here.",
  "價格": "This price is acceptable.",
  "禁止": "Smoking is prohibited here.",
  "請": "Please wait a moment.",
  "自動": "This door is an automatic door.",
  "前台": "Please go to the front desk to check in.",
  "便利商店": "The convenience store is open twenty-four hours.",
  "電": "My phone is almost out of battery.",
  "樓梯": "The elevator is broken, so we will take the stairs.",
  "廁所": "Excuse me, where is the restroom?",
  "男": "The men's restroom is on the right.",
  "女": "The women's restroom is on the left.",
  "免費": "This event is free to attend.",
  "排隊": "You need to line up at this shop.",
  "拉": "The door says pull.",
  "開": "Please help me open the door.",
  "關": "Please turn off the lights before leaving.",
  "注意": "Please pay attention to safety.",
  "東西南北": "I am still not very good at telling east, west, south, and north apart.",
  "蝦": "This dish has shrimp.",
  "牡蠣": "There are oysters in oyster omelets.",
  "魷魚": "The night market has grilled squid.",
  "臭豆腐": "Stinky tofu is a famous Taiwanese street food.",
  "貢丸湯": "I ordered a bowl of pork ball soup.",
  "青蔥": "There are scallions on top of this soup.",
  "潮流": "This design fits young people's trends very well.",
  "低溫": "This product needs to be stored at a low temperature.",
  "項目": "This project starts next week.",
  "方式": "We need to change the way we communicate."
};

const c = (traditional, simplified, pinyin, meaning, sentenceTraditional, sentenceSimplified, sentencePinyin, category) => ({
  traditional,
  simplified,
  pinyin,
  meaning,
  sentenceTraditional,
  sentenceSimplified,
  sentencePinyin,
  sentenceEnglish: sentenceEnglishByTerm[traditional] || "",
  category
});

window.defaultCards = [
  c("企業文化", "企业文化", "qǐyè wénhuà", "company culture", "這家公司的企業文化很開放。", "这家公司的企业文化很开放。", "Zhè jiā gōngsī de qǐyè wénhuà hěn kāifàng.", "Business"),
  c("投資", "投资", "tóuzī", "investment; to invest", "我們正在討論新的投資機會。", "我们正在讨论新的投资机会。", "Wǒmen zhèngzài tǎolùn xīn de tóuzī jīhuì.", "Business"),
  c("投資人", "投资人", "tóuzīrén", "investor", "他是一位科技公司的投資人。", "他是一位科技公司的投资人。", "Tā shì yí wèi kējì gōngsī de tóuzīrén.", "Business"),
  c("收入", "收入", "shōurù", "income; revenue", "這家公司今年的收入增加了。", "这家公司今年的收入增加了。", "Zhè jiā gōngsī jīnnián de shōurù zēngjiā le.", "Business"),
  c("利潤", "利润", "lìrùn", "profit", "我們需要提高這個產品的利潤。", "我们需要提高这个产品的利润。", "Wǒmen xūyào tígāo zhège chǎnpǐn de lìrùn.", "Business"),
  c("競爭", "竞争", "jìngzhēng", "competition; to compete", "這個市場競爭很激烈。", "这个市场竞争很激烈。", "Zhège shìchǎng jìngzhēng hěn jīliè.", "Business"),
  c("市場", "市场", "shìchǎng", "market", "台灣市場對新品牌很友善。", "台湾市场对新品牌很友善。", "Táiwān shìchǎng duì xīn pǐnpái hěn yǒushàn.", "Business"),
  c("國際", "国际", "guójì", "international", "這是我們第一次參加國際展會。", "这是我们第一次参加国际展会。", "Zhè shì wǒmen dì yī cì cānjiā guójì zhǎnhuì.", "Business"),
  c("政府", "政府", "zhèngfǔ", "government", "政府最近發布了新的政策。", "政府最近发布了新的政策。", "Zhèngfǔ zuìjìn fābù le xīn de zhèngcè.", "News"),
  c("政策", "政策", "zhèngcè", "policy", "這項政策會影響很多公司。", "这项政策会影响很多公司。", "Zhè xiàng zhèngcè huì yǐngxiǎng hěn duō gōngsī.", "News"),
  c("內容", "内容", "nèiróng", "content", "這個內容很適合社群媒體。", "这个内容很适合社群媒体。", "Zhège nèiróng hěn shìhé shèqún méitǐ.", "Marketing"),
  c("品牌", "品牌", "pǐnpái", "brand", "這個品牌最近很受歡迎。", "这个品牌最近很受欢迎。", "Zhège pǐnpái zuìjìn hěn shòu huānyíng.", "Marketing"),
  c("品牌合作", "品牌合作", "pǐnpái hézuò", "brand partnership", "我負責品牌合作和內容企劃。", "我负责品牌合作和内容企划。", "Wǒ fùzé pǐnpái hézuò hé nèiróng qǐhuà.", "Marketing"),
  c("影片", "影片", "yǐngpiàn", "video; film clip", "這支影片的流量很好。", "这支影片的流量很好。", "Zhè zhī yǐngpiàn de liúliàng hěn hǎo.", "Marketing"),
  c("觀眾", "观众", "guānzhòng", "audience; viewers", "我們要了解觀眾真正想看什麼。", "我们要了解观众真正想看什么。", "Wǒmen yào liǎojiě guānzhòng zhēnzhèng xiǎng kàn shénme.", "Marketing"),
  c("流量", "流量", "liúliàng", "traffic; views; reach", "這篇文章帶來很多流量。", "这篇文章带来很多流量。", "Zhè piān wénzhāng dài lái hěn duō liúliàng.", "Marketing"),
  c("熱度", "热度", "rèdù", "buzz; popularity", "這個話題最近熱度很高。", "这个话题最近热度很高。", "Zhège huàtí zuìjìn rèdù hěn gāo.", "Marketing"),
  c("推薦", "推荐", "tuījiàn", "to recommend", "你可以推薦一家好餐廳嗎？", "你可以推荐一家好餐厅吗？", "Nǐ kěyǐ tuījiàn yì jiā hǎo cāntīng ma?", "Daily"),
  c("熱賣", "热卖", "rèmài", "best-selling", "這款飲料最近熱賣。", "这款饮料最近热卖。", "Zhè kuǎn yǐnliào zuìjìn rèmài.", "Marketing"),
  c("限量版", "限量版", "xiànliàng bǎn", "limited edition", "這是限量版，所以很快就賣完。", "这是限量版，所以很快就卖完。", "Zhè shì xiànliàng bǎn, suǒyǐ hěn kuài jiù mài wán.", "Marketing"),
  c("體驗", "体验", "tǐyàn", "experience; to experience", "使用者體驗需要再優化。", "使用者体验需要再优化。", "Shǐyòngzhě tǐyàn xūyào zài yōuhuà.", "Tech"),
  c("高效", "高效", "gāoxiào", "efficient; high efficiency", "這個工具可以幫我們高效完成工作。", "这个工具可以帮我们高效完成工作。", "Zhège gōngjù kěyǐ bāng wǒmen gāoxiào wánchéng gōngzuò.", "Work"),
  c("專業", "专业", "zhuānyè", "professional; specialized", "他的簡報看起來很專業。", "他的简报看起来很专业。", "Tā de jiǎnbào kàn qǐlái hěn zhuānyè.", "Work"),
  c("多功能", "多功能", "duō gōngnéng", "multifunctional", "這是一個多功能的剪輯工具。", "这是一个多功能的剪辑工具。", "Zhè shì yí ge duō gōngnéng de jiǎnjí gōngjù.", "Tech"),
  c("產品", "产品", "chǎnpǐn", "product", "這個產品的定位很清楚。", "这个产品的定位很清楚。", "Zhège chǎnpǐn de dìngwèi hěn qīngchǔ.", "Business"),
  c("簡報", "简报", "jiǎnbào", "presentation deck", "我明天要做一份簡報。", "我明天要做一份简报。", "Wǒ míngtiān yào zuò yí fèn jiǎnbào.", "Work"),
  c("會議", "会议", "huìyì", "meeting", "下午的會議改到三點。", "下午的会议改到三点。", "Xiàwǔ de huìyì gǎi dào sān diǎn.", "Work"),
  c("團隊", "团队", "tuánduì", "team", "我們的團隊正在做內容企劃。", "我们的团队正在做内容企划。", "Wǒmen de tuánduì zhèngzài zuò nèiróng qǐhuà.", "Work"),
  c("客戶", "客户", "kèhù", "client; customer", "這位客戶想看新的方案。", "这位客户想看新的方案。", "Zhè wèi kèhù xiǎng kàn xīn de fāng'àn.", "Work"),
  c("方案", "方案", "fāng'àn", "proposal; plan", "請把方案寄給客戶。", "请把方案寄给客户。", "Qǐng bǎ fāng'àn jì gěi kèhù.", "Work"),
  c("合作", "合作", "hézuò", "to collaborate; cooperation", "我們希望下個月開始合作。", "我们希望下个月开始合作。", "Wǒmen xīwàng xià ge yuè kāishǐ hézuò.", "Work"),
  c("創作者", "创作者", "chuàngzuòzhě", "creator", "這位創作者的影片很有創意。", "这位创作者的影片很有创意。", "Zhè wèi chuàngzuòzhě de yǐngpiàn hěn yǒu chuàngyì.", "Marketing"),
  c("創意", "创意", "chuàngyì", "creative idea; concept", "這個廣告的創意很新。", "这个广告的创意很新。", "Zhège guǎnggào de chuàngyì hěn xīn.", "Marketing"),
  c("創新", "创新", "chuàngxīn", "innovation; to innovate", "公司需要更多創新。", "公司需要更多创新。", "Gōngsī xūyào gèng duō chuàngxīn.", "Business"),
  c("優化", "优化", "yōuhuà", "to optimize", "這個功能還需要優化。", "这个功能还需要优化。", "Zhège gōngnéng hái xūyào yōuhuà.", "Tech"),
  c("發展", "发展", "fāzhǎn", "development; to develop", "這個產業發展很快。", "这个产业发展很快。", "Zhège chǎnyè fāzhǎn hěn kuài.", "News"),
  c("結果", "结果", "jiéguǒ", "result", "測試結果比預期更好。", "测试结果比预期更好。", "Cèshì jiéguǒ bǐ yùqí gèng hǎo.", "News"),
  c("影響", "影响", "yǐngxiǎng", "impact; to affect", "這個改變會影響使用者體驗。", "这个改变会影响使用者体验。", "Zhège gǎibiàn huì yǐngxiǎng shǐyòngzhě tǐyàn.", "News"),
  c("趨勢", "趋势", "qūshì", "trend", "AI 是今年很重要的趨勢。", "AI 是今年很重要的趋势。", "AI shì jīnnián hěn zhòngyào de qūshì.", "News"),
  c("數據分析", "数据分析", "shùjù fēnxī", "data analysis", "我們用數據分析來改善內容。", "我们用数据分析来改善内容。", "Wǒmen yòng shùjù fēnxī lái gǎishàn nèiróng.", "Tech"),
  c("工作內容", "工作内容", "gōngzuò nèiróng", "job responsibilities; work content", "你可以說明一下工作內容嗎？", "你可以说明一下工作内容吗？", "Nǐ kěyǐ shuōmíng yíxià gōngzuò nèiróng ma?", "Work"),
  c("提到", "提到", "tídào", "to mention", "他在會議中提到新的策略。", "他在会议中提到新的策略。", "Tā zài huìyì zhōng tídào xīn de cèlüè.", "Work"),
  c("有效", "有效", "yǒuxiào", "effective; valid", "這個方法很有效。", "这个方法很有效。", "Zhège fāngfǎ hěn yǒuxiào.", "Work"),
  c("年輕", "年轻", "niánqīng", "young", "這個品牌很受年輕人歡迎。", "这个品牌很受年轻人欢迎。", "Zhège pǐnpái hěn shòu niánqīng rén huānyíng.", "Daily"),
  c("年輕族群", "年轻族群", "niánqīng zúqún", "younger demographic", "這個活動主要吸引年輕族群。", "这个活动主要吸引年轻族群。", "Zhège huódòng zhǔyào xīyǐn niánqīng zúqún.", "Marketing"),
  c("危險", "危险", "wēixiǎn", "dangerous; danger", "這個路口有點危險。", "这个路口有点危险。", "Zhège lùkǒu yǒu diǎn wēixiǎn.", "Daily"),
  c("事件描述", "事件描述", "shìjiàn miáoshù", "event description", "請寫一段清楚的事件描述。", "请写一段清楚的事件描述。", "Qǐng xiě yí duàn qīngchǔ de shìjiàn miáoshù.", "News"),
  c("原因", "原因", "yuányīn", "reason; cause", "我們需要找出真正的原因。", "我们需要找出真正的原因。", "Wǒmen xūyào zhǎo chū zhēnzhèng de yuányīn.", "News"),
  c("報告", "报告", "bàogào", "report; to report; presentation", "我需要在會議前完成這份報告。", "我需要在会议前完成这份报告。", "Wǒ xūyào zài huìyì qián wánchéng zhè fèn bàogào.", "Work"),
  c("報導", "报导", "bàodǎo", "news report; media coverage; to report in the media", "這篇報導提到市場趨勢。", "这篇报导提到市场趋势。", "Zhè piān bàodǎo tídào shìchǎng qūshì.", "News"),
  c("小吃", "小吃", "xiǎochī", "snack; street food", "夜市有很多好吃的小吃。", "夜市有很多好吃的小吃。", "Yèshì yǒu hěn duō hǎochī de xiǎochī.", "Food"),
  c("小籠包", "小笼包", "xiǎolóngbāo", "soup dumplings", "這家店的小籠包很有名。", "这家店的小笼包很有名。", "Zhè jiā diàn de xiǎolóngbāo hěn yǒumíng.", "Food"),
  c("滷肉飯", "卤肉饭", "lǔròufàn", "braised pork rice", "我想點一碗滷肉飯。", "我想点一碗卤肉饭。", "Wǒ xiǎng diǎn yì wǎn lǔròufàn.", "Food"),
  c("牛肉麵", "牛肉面", "niúròu miàn", "beef noodle soup", "台灣的牛肉麵很好吃。", "台湾的牛肉面很好吃。", "Táiwān de niúròu miàn hěn hǎochī.", "Food"),
  c("雞排", "鸡排", "jīpái", "fried chicken cutlet", "夜市的雞排很大。", "夜市的鸡排很大。", "Yèshì de jīpái hěn dà.", "Food"),
  c("豬肉", "猪肉", "zhūròu", "pork", "這道菜裡面有豬肉。", "这道菜里面有猪肉。", "Zhè dào cài lǐmiàn yǒu zhūròu.", "Food"),
  c("牛肉", "牛肉", "niúròu", "beef", "我比較喜歡牛肉。", "我比较喜欢牛肉。", "Wǒ bǐjiào xǐhuān niúròu.", "Food"),
  c("雞肉", "鸡肉", "jīròu", "chicken meat", "這份便當有雞肉。", "这份便当有鸡肉。", "Zhè fèn biàndāng yǒu jīròu.", "Food"),
  c("鴨肉", "鸭肉", "yāròu", "duck meat", "鴨肉湯是這裡的招牌。", "鸭肉汤是这里的招牌。", "Yāròu tāng shì zhèlǐ de zhāopái.", "Food"),
  c("羊肉", "羊肉", "yángròu", "lamb; mutton", "冬天很多人喜歡吃羊肉爐。", "冬天很多人喜欢吃羊肉炉。", "Dōngtiān hěn duō rén xǐhuān chī yángròu lú.", "Food"),
  c("蛋", "蛋", "dàn", "egg", "可以幫我加一顆蛋嗎？", "可以帮我加一颗蛋吗？", "Kěyǐ bāng wǒ jiā yì kē dàn ma?", "Food"),
  c("海鮮", "海鲜", "hǎixiān", "seafood", "這家餐廳的海鮮很新鮮。", "这家餐厅的海鲜很新鲜。", "Zhè jiā cāntīng de hǎixiān hěn xīnxiān.", "Food"),
  c("什錦", "什锦", "shíjǐn", "assorted; mixed", "我點了一碗什錦湯麵。", "我点了一碗什锦汤面。", "Wǒ diǎn le yì wǎn shíjǐn tāngmiàn.", "Food"),
  c("湯", "汤", "tāng", "soup", "這碗湯有點辣。", "这碗汤有点辣。", "Zhè wǎn tāng yǒu diǎn là.", "Food"),
  c("醬", "酱", "jiàng", "sauce; paste", "這個醬很適合配雞排。", "这个酱很适合配鸡排。", "Zhège jiàng hěn shìhé pèi jīpái.", "Food"),
  c("米糕", "米糕", "mǐgāo", "sticky rice cake", "台南的米糕很有名。", "台南的米糕很有名。", "Táinán de mǐgāo hěn yǒumíng.", "Food"),
  c("麻辣鍋", "麻辣锅", "málà guō", "spicy hot pot", "晚上我們去吃麻辣鍋。", "晚上我们去吃麻辣锅。", "Wǎnshàng wǒmen qù chī málà guō.", "Food"),
  c("酸辣湯", "酸辣汤", "suānlà tāng", "hot and sour soup", "我想點一碗酸辣湯。", "我想点一碗酸辣汤。", "Wǒ xiǎng diǎn yì wǎn suānlà tāng.", "Food"),
  c("蒸", "蒸", "zhēng", "to steam", "這道菜是用蒸的。", "这道菜是用蒸的。", "Zhè dào cài shì yòng zhēng de.", "Food"),
  c("煮", "煮", "zhǔ", "to boil; to cook", "牛肉麵要煮久一點。", "牛肉面要煮久一点。", "Niúròu miàn yào zhǔ jiǔ yì diǎn.", "Food"),
  c("炒", "炒", "chǎo", "to stir-fry", "我想吃炒飯。", "我想吃炒饭。", "Wǒ xiǎng chī chǎofàn.", "Food"),
  c("烤", "烤", "kǎo", "to roast; to grill", "這個雞肉是烤的。", "这个鸡肉是烤的。", "Zhège jīròu shì kǎo de.", "Food"),
  c("煎", "煎", "jiān", "to pan-fry", "早餐我吃煎蛋。", "早餐我吃煎蛋。", "Zǎocān wǒ chī jiāndàn.", "Food"),
  c("炸", "炸", "zhá", "to deep-fry", "雞排通常是炸的。", "鸡排通常是炸的。", "Jīpái tōngcháng shì zhá de.", "Food"),
  c("滷", "卤", "lǔ", "to braise in soy sauce", "這家店的滷味很受歡迎。", "这家店的卤味很受欢迎。", "Zhè jiā diàn de lǔwèi hěn shòu huānyíng.", "Food"),
  c("飯", "饭", "fàn", "rice; meal", "我午餐想吃飯。", "我午餐想吃饭。", "Wǒ wǔcān xiǎng chī fàn.", "Food"),
  c("麵", "面", "miàn", "noodles", "這碗麵味道很好。", "这碗面味道很好。", "Zhè wǎn miàn wèidào hěn hǎo.", "Food"),
  c("粥", "粥", "zhōu", "congee", "早上吃粥很舒服。", "早上吃粥很舒服。", "Zǎoshang chī zhōu hěn shūfú.", "Food"),
  c("冰水", "冰水", "bīng shuǐ", "ice water", "可以給我一杯冰水嗎？", "可以给我一杯冰水吗？", "Kěyǐ gěi wǒ yì bēi bīng shuǐ ma?", "Drink"),
  c("熱水", "热水", "rè shuǐ", "hot water", "我想要一杯熱水。", "我想要一杯热水。", "Wǒ xiǎng yào yì bēi rè shuǐ.", "Drink"),
  c("少冰", "少冰", "shǎo bīng", "less ice", "珍珠奶茶我要少冰。", "珍珠奶茶我要少冰。", "Zhēnzhū nǎichá wǒ yào shǎo bīng.", "Drink"),
  c("微冰", "微冰", "wēi bīng", "light ice", "這杯飲料請做微冰。", "这杯饮料请做微冰。", "Zhè bēi yǐnliào qǐng zuò wēi bīng.", "Drink"),
  c("去冰", "去冰", "qù bīng", "no ice", "我想要無糖去冰。", "我想要无糖去冰。", "Wǒ xiǎng yào wú táng qù bīng.", "Drink"),
  c("全糖", "全糖", "quán táng", "full sugar", "這杯是全糖，會比較甜。", "这杯是全糖，会比较甜。", "Zhè bēi shì quán táng, huì bǐjiào tián.", "Drink"),
  c("半糖", "半糖", "bàn táng", "half sugar", "奶茶請做半糖。", "奶茶请做半糖。", "Nǎichá qǐng zuò bàn táng.", "Drink"),
  c("微糖", "微糖", "wēi táng", "light sugar", "我平常喝微糖。", "我平常喝微糖。", "Wǒ píngcháng hē wēi táng.", "Drink"),
  c("少糖", "少糖", "shǎo táng", "less sugar", "這杯飲料少糖就好。", "这杯饮料少糖就好。", "Zhè bēi yǐnliào shǎo táng jiù hǎo.", "Drink"),
  c("無糖", "无糖", "wú táng", "no sugar", "綠茶我要無糖。", "绿茶我要无糖。", "Lǜchá wǒ yào wú táng.", "Drink"),
  c("入口", "入口", "rùkǒu", "entrance", "捷運站入口在前面。", "地铁站入口在前面。", "Jiéyùnzhàn rùkǒu zài qiánmiàn.", "Signs"),
  c("出口", "出口", "chūkǒu", "exit", "請從右邊的出口出去。", "请从右边的出口出去。", "Qǐng cóng yòubiān de chūkǒu chūqù.", "Signs"),
  c("電梯", "电梯", "diàntī", "elevator", "電梯在左邊。", "电梯在左边。", "Diàntī zài zuǒbiān.", "Signs"),
  c("樓", "楼", "lóu", "floor; building", "餐廳在二樓。", "餐厅在二楼。", "Cāntīng zài èr lóu.", "Signs"),
  c("路", "路", "lù", "road", "這條路晚上很熱鬧。", "这条路晚上很热闹。", "Zhè tiáo lù wǎnshàng hěn rènào.", "Signs"),
  c("街", "街", "jiē", "street", "夜市在那條街。", "夜市在那条街。", "Yèshì zài nà tiáo jiē.", "Signs"),
  c("號", "号", "hào", "number", "地址是中山路十號。", "地址是中山路十号。", "Dìzhǐ shì Zhōngshān Lù shí hào.", "Signs"),
  c("藥局", "药局", "yàojú", "pharmacy", "附近有藥局嗎？", "附近有药局吗？", "Fùjìn yǒu yàojú ma?", "Signs"),
  c("餐廳", "餐厅", "cāntīng", "restaurant", "這家餐廳需要訂位。", "这家餐厅需要订位。", "Zhè jiā cāntīng xūyào dìngwèi.", "Signs"),
  c("公司", "公司", "gōngsī", "company", "我今天要去客戶公司。", "我今天要去客户公司。", "Wǒ jīntiān yào qù kèhù gōngsī.", "Business"),
  c("捷運", "捷运", "jiéyùn", "MRT; metro", "我每天搭捷運去公司。", "我每天搭捷运去公司。", "Wǒ měitiān dā jiéyùn qù gōngsī.", "Signs"),
  c("月臺", "月台", "yuètái", "platform", "列車快到了，請在月臺等。", "列车快到了，请在月台等。", "Lièchē kuài dào le, qǐng zài yuètái děng.", "Signs"),
  c("列車", "列车", "lièchē", "train", "這班列車往台北。", "这班列车往台北。", "Zhè bān lièchē wǎng Táiběi.", "Signs"),
  c("公車", "公车", "gōngchē", "bus", "我們可以坐公車去夜市。", "我们可以坐公车去夜市。", "Wǒmen kěyǐ zuò gōngchē qù yèshì.", "Signs"),
  c("巷", "巷", "xiàng", "alley", "這家咖啡店在小巷裡。", "这家咖啡店在小巷里。", "Zhè jiā kāfēi diàn zài xiǎo xiàng lǐ.", "Signs"),
  c("弄", "弄", "lòng", "lane; alley branch", "地址寫的是三弄五號。", "地址写的是三弄五号。", "Dìzhǐ xiě de shì sān lòng wǔ hào.", "Signs"),
  c("段", "段", "duàn", "section", "公司在忠孝東路四段。", "公司在忠孝东路四段。", "Gōngsī zài Zhōngxiào Dōnglù sì duàn.", "Signs"),
  c("最近", "最近", "zuìjìn", "recently; lately", "這個品牌最近很紅。", "这个品牌最近很红。", "Zhège pǐnpái zuìjìn hěn hóng.", "Daily"),
  c("年糕", "年糕", "niángāo", "rice cake", "過年時很多人會吃年糕。", "过年时很多人会吃年糕。", "Guònián shí hěn duō rén huì chī niángāo.", "Food"),
  c("燒賣", "烧卖", "shāomài", "shumai; steamed dumpling", "這家港式餐廳的燒賣很好吃。", "这家港式餐厅的烧卖很好吃。", "Zhè jiā Gǎngshì cāntīng de shāomài hěn hǎochī.", "Food"),
  c("點心", "点心", "diǎnxīn", "dim sum; snack", "下午我們吃一點點心。", "下午我们吃一点点心。", "Xiàwǔ wǒmen chī yì diǎn diǎnxīn.", "Food"),
  c("冰淇淋", "冰淇淋", "bīngqílín", "ice cream", "天氣很熱，我想吃冰淇淋。", "天气很热，我想吃冰淇淋。", "Tiānqì hěn rè, wǒ xiǎng chī bīngqílín.", "Food"),
  c("甜點", "甜点", "tiándiǎn", "dessert", "飯後我們點了甜點。", "饭后我们点了甜点。", "Fàn hòu wǒmen diǎn le tiándiǎn.", "Food"),
  c("客氣", "客气", "kèqì", "polite; courteous", "不用客氣，這是小事。", "不用客气，这是小事。", "Bú yòng kèqì, zhè shì xiǎoshì.", "Daily"),
  c("對錯", "对错", "duìcuò", "right and wrong", "先不要急著判斷對錯。", "先不要急着判断对错。", "Xiān bú yào jízhe pànduàn duìcuò.", "Daily"),
  c("老闆娘", "老板娘", "lǎobǎnniáng", "female shop owner; boss's wife", "老闆娘推薦我們招牌菜。", "老板娘推荐我们招牌菜。", "Lǎobǎnniáng tuījiàn wǒmen zhāopái cài.", "Daily"),
  c("工作人員", "工作人员", "gōngzuò rényuán", "staff member", "請問工作人員入口在哪裡？", "请问工作人员入口在哪里？", "Qǐngwèn gōngzuò rényuán rùkǒu zài nǎlǐ?", "Work"),
  c("按鈕", "按钮", "ànniǔ", "button", "請按這個按鈕確認。", "请按这个按钮确认。", "Qǐng àn zhège ànniǔ quèrèn.", "Tech"),
  c("宵夜", "宵夜", "xiāoyè", "late-night meal", "晚上十一點後我們去吃宵夜。", "晚上十一点后我们去吃宵夜。", "Wǎnshàng shíyī diǎn hòu wǒmen qù chī xiāoyè.", "Food"),
  c("大樓", "大楼", "dàlóu", "building", "會議室在那棟大樓裡。", "会议室在那栋大楼里。", "Huìyìshì zài nà dòng dàlóu lǐ.", "Signs"),
  c("公寓", "公寓", "gōngyù", "apartment", "他住在捷運站附近的公寓。", "他住在地铁站附近的公寓。", "Tā zhù zài jiéyùnzhàn fùjìn de gōngyù.", "Daily"),
  c("酒店", "酒店", "jiǔdiàn", "hotel", "我們的酒店離機場很近。", "我们的酒店离机场很近。", "Wǒmen de jiǔdiàn lí jīchǎng hěn jìn.", "Travel"),
  c("商場", "商场", "shāngchǎng", "shopping mall; commercial space", "商場裡有很多餐廳。", "商场里有很多餐厅。", "Shāngchǎng lǐ yǒu hěn duō cāntīng.", "Signs"),
  c("銀行", "银行", "yínháng", "bank", "銀行下午三點半關門。", "银行下午三点半关门。", "Yínháng xiàwǔ sān diǎn bàn guānmén.", "Signs"),
  c("醫院", "医院", "yīyuàn", "hospital", "醫院在路口旁邊。", "医院在路口旁边。", "Yīyuàn zài lùkǒu pángbiān.", "Signs"),
  c("診所", "诊所", "zhěnsuǒ", "clinic", "附近有牙醫診所嗎？", "附近有牙医诊所吗？", "Fùjìn yǒu yáyī zhěnsuǒ ma?", "Signs"),
  c("行銷", "行销", "xíngxiāo", "marketing", "她負責品牌行銷。", "她负责品牌行销。", "Tā fùzé pǐnpái xíngxiāo.", "Marketing"),
  c("影片製作", "影片制作", "yǐngpiàn zhìzuò", "video production", "我們最近在做影片製作。", "我们最近在做影片制作。", "Wǒmen zuìjìn zài zuò yǐngpiàn zhìzuò.", "Marketing"),
  c("宣傳", "宣传", "xuānchuán", "promotion; publicity", "這次活動需要更多宣傳。", "这次活动需要更多宣传。", "Zhè cì huódòng xūyào gèng duō xuānchuán.", "Marketing"),
  c("資訊", "资讯", "zīxùn", "information; tech information", "請把活動資訊發給我。", "请把活动资讯发给我。", "Qǐng bǎ huódòng zīxùn fā gěi wǒ.", "Tech"),
  c("辣椒", "辣椒", "làjiāo", "chili pepper", "這個醬裡有很多辣椒。", "这个酱里有很多辣椒。", "Zhège jiàng lǐ yǒu hěn duō làjiāo.", "Food"),
  c("青菜", "青菜", "qīngcài", "greens; vegetables", "我想多點一份青菜。", "我想多点一份青菜。", "Wǒ xiǎng duō diǎn yí fèn qīngcài.", "Food"),
  c("高麗菜", "高丽菜", "gāolìcài", "cabbage", "水餃裡面有高麗菜。", "水饺里面有高丽菜。", "Shuǐjiǎo lǐmiàn yǒu gāolìcài.", "Food"),
  c("竹筍", "竹笋", "zhúsǔn", "bamboo shoots", "這碗湯有竹筍。", "这碗汤有竹笋。", "Zhè wǎn tāng yǒu zhúsǔn.", "Food"),
  c("紅蘿蔔", "红萝卜", "hóngluóbo", "carrot", "紅蘿蔔可以讓湯更甜。", "红萝卜可以让汤更甜。", "Hóngluóbo kěyǐ ràng tāng gèng tián.", "Food"),
  c("洋蔥", "洋葱", "yángcōng", "onion", "牛肉飯裡有洋蔥。", "牛肉饭里有洋葱。", "Niúròu fàn lǐ yǒu yángcōng.", "Food"),
  c("饅頭", "馒头", "mán tou", "steamed bun", "早餐我吃饅頭配豆漿。", "早餐我吃馒头配豆浆。", "Zǎocān wǒ chī mán tou pèi dòujiāng.", "Food"),
  c("薯條", "薯条", "shǔtiáo", "fries", "小朋友很喜歡薯條。", "小朋友很喜欢薯条。", "Xiǎopéngyǒu hěn xǐhuān shǔtiáo.", "Food"),
  c("中份", "中份", "zhōngfèn", "medium portion", "我要一份中份薯條。", "我要一份中份薯条。", "Wǒ yào yí fèn zhōngfèn shǔtiáo.", "Food"),
  c("鍋貼", "锅贴", "guōtiē", "pan-fried dumplings", "這家店的鍋貼很脆。", "这家店的锅贴很脆。", "Zhè jiā diàn de guōtiē hěn cuì.", "Food"),
  c("肉圓", "肉圆", "ròuyuán", "Taiwanese meatball", "彰化肉圓很有名。", "彰化肉圆很有名。", "Zhānghuà ròuyuán hěn yǒumíng.", "Food"),
  c("快炒", "快炒", "kuàichǎo", "quick stir-fry; stir-fry restaurant", "晚上我們去快炒店吃飯。", "晚上我们去快炒店吃饭。", "Wǎnshàng wǒmen qù kuàichǎo diàn chīfàn.", "Food"),
  c("香菇", "香菇", "xiānggū", "shiitake mushroom", "這碗湯有香菇。", "这碗汤有香菇。", "Zhè wǎn tāng yǒu xiānggū.", "Food"),
  c("醬油", "酱油", "jiàngyóu", "soy sauce", "鍋貼可以沾一點醬油。", "锅贴可以蘸一点酱油。", "Guōtiē kěyǐ zhān yì diǎn jiàngyóu.", "Food"),
  c("少鹽", "少盐", "shǎo yán", "less salt", "這道菜可以少鹽嗎？", "这道菜可以少盐吗？", "Zhè dào cài kěyǐ shǎo yán ma?", "Food"),
  c("蔥油", "葱油", "cōngyóu", "scallion oil", "蔥油餅是很常見的小吃。", "葱油饼是很常见的小吃。", "Cōngyóu bǐng shì hěn chángjiàn de xiǎochī.", "Food"),
  c("糖醋排骨", "糖醋排骨", "tángcù páigǔ", "sweet and sour pork ribs", "糖醋排骨酸酸甜甜的。", "糖醋排骨酸酸甜甜的。", "Tángcù páigǔ suān suān tián tián de.", "Food"),
  c("滿滿", "满满", "mǎnmǎn", "full of; packed with", "這碗麵料滿滿。", "这碗面料满满。", "Zhè wǎn miàn liào mǎnmǎn.", "Daily"),
  c("空", "空", "kōng", "empty; available", "這個座位是空的嗎？", "这个座位是空的吗？", "Zhège zuòwèi shì kōng de ma?", "Daily"),
  c("停車", "停车", "tíngchē", "parking; to park", "這裡不能停車。", "这里不能停车。", "Zhèlǐ bù néng tíngchē.", "Signs"),
  c("地下", "地下", "dìxià", "underground", "停車場在地下二樓。", "停车场在地下二楼。", "Tíngchēchǎng zài dìxià èr lóu.", "Signs"),
  c("特價", "特价", "tèjià", "special price; sale", "這個產品今天特價。", "这个产品今天特价。", "Zhège chǎnpǐn jīntiān tèjià.", "Shopping"),
  c("所有", "所有", "suǒyǒu", "all; every", "所有資料都在這裡。", "所有资料都在这里。", "Suǒyǒu zīliào dōu zài zhèlǐ.", "Daily"),
  c("價格", "价格", "jiàgé", "price", "這個價格可以接受。", "这个价格可以接受。", "Zhège jiàgé kěyǐ jiēshòu.", "Shopping"),
  c("禁止", "禁止", "jìnzhǐ", "prohibited; forbid", "這裡禁止吸菸。", "这里禁止吸烟。", "Zhèlǐ jìnzhǐ xīyān.", "Signs"),
  c("請", "请", "qǐng", "please", "請稍等一下。", "请稍等一下。", "Qǐng shāo děng yíxià.", "Daily"),
  c("自動", "自动", "zìdòng", "automatic", "這扇門是自動門。", "这扇门是自动门。", "Zhè shàn mén shì zìdòng mén.", "Signs"),
  c("前台", "前台", "qiántái", "front desk", "請到前台辦理入住。", "请到前台办理入住。", "Qǐng dào qiántái bànlǐ rùzhù.", "Travel"),
  c("便利商店", "便利商店", "biànlì shāngdiàn", "convenience store", "便利商店二十四小時營業。", "便利商店二十四小时营业。", "Biànlì shāngdiàn èrshísì xiǎoshí yíngyè.", "Daily"),
  c("電", "电", "diàn", "electricity", "手機快沒電了。", "手机快没电了。", "Shǒujī kuài méi diàn le.", "Daily"),
  c("樓梯", "楼梯", "lóutī", "stairs", "電梯壞了，我們走樓梯。", "电梯坏了，我们走楼梯。", "Diàntī huài le, wǒmen zǒu lóutī.", "Signs"),
  c("廁所", "厕所", "cèsuǒ", "restroom", "請問廁所在哪裡？", "请问厕所在哪里？", "Qǐngwèn cèsuǒ zài nǎlǐ?", "Signs"),
  c("男", "男", "nán", "male; man", "男廁所在右邊。", "男厕所在右边。", "Nán cèsuǒ zài yòubiān.", "Signs"),
  c("女", "女", "nǚ", "female; woman", "女廁所在左邊。", "女厕所在左边。", "Nǚ cèsuǒ zài zuǒbiān.", "Signs"),
  c("免費", "免费", "miǎnfèi", "free of charge", "這個活動免費參加。", "这个活动免费参加。", "Zhège huódòng miǎnfèi cānjiā.", "Daily"),
  c("排隊", "排队", "páiduì", "to line up", "這家店需要排隊。", "这家店需要排队。", "Zhè jiā diàn xūyào páiduì.", "Daily"),
  c("拉", "拉", "lā", "to pull", "門上寫著拉。", "门上写着拉。", "Mén shàng xiězhe lā.", "Signs"),
  c("開", "开", "kāi", "to open; turn on", "請幫我開門。", "请帮我开门。", "Qǐng bāng wǒ kāi mén.", "Daily"),
  c("關", "关", "guān", "to close; turn off", "離開前請關燈。", "离开前请关灯。", "Líkāi qián qǐng guān dēng.", "Daily"),
  c("注意", "注意", "zhùyì", "pay attention; notice", "請注意安全。", "请注意安全。", "Qǐng zhùyì ānquán.", "Signs"),
  c("東西南北", "东西南北", "dōng xī nán běi", "east, west, south, north", "我還不太會分東西南北。", "我还不太会分东西南北。", "Wǒ hái bú tài huì fēn dōng xī nán běi.", "Daily"),
  c("蝦", "虾", "xiā", "shrimp", "這道菜有蝦。", "这道菜有虾。", "Zhè dào cài yǒu xiā.", "Food"),
  c("牡蠣", "牡蛎", "mǔlì", "oyster", "蚵仔煎裡有牡蠣。", "蚵仔煎里有牡蛎。", "Ézǐjiān lǐ yǒu mǔlì.", "Food"),
  c("魷魚", "鱿鱼", "yóuyú", "squid", "夜市有烤魷魚。", "夜市有烤鱿鱼。", "Yèshì yǒu kǎo yóuyú.", "Food"),
  c("臭豆腐", "臭豆腐", "chòu dòufu", "stinky tofu", "臭豆腐是台灣有名的小吃。", "臭豆腐是台湾有名的小吃。", "Chòu dòufu shì Táiwān yǒumíng de xiǎochī.", "Food"),
  c("貢丸湯", "贡丸汤", "gòngwán tāng", "pork ball soup", "我點了一碗貢丸湯。", "我点了一碗贡丸汤。", "Wǒ diǎn le yì wǎn gòngwán tāng.", "Food"),
  c("青蔥", "青葱", "qīngcōng", "scallion", "這碗湯上面有青蔥。", "这碗汤上面有青葱。", "Zhè wǎn tāng shàngmiàn yǒu qīngcōng.", "Food"),
  c("潮流", "潮流", "cháoliú", "trend; current style", "這個設計很符合年輕潮流。", "这个设计很符合年轻潮流。", "Zhège shèjì hěn fúhé niánqīng cháoliú.", "Marketing"),
  c("低溫", "低温", "dīwēn", "low temperature", "這個產品需要低溫保存。", "这个产品需要低温保存。", "Zhège chǎnpǐn xūyào dīwēn bǎocún.", "Daily"),
  c("項目", "项目", "xiàngmù", "project; item", "這個項目下週開始。", "这个项目下周开始。", "Zhège xiàngmù xià zhōu kāishǐ.", "Work"),
  c("方式", "方式", "fāngshì", "method; way", "我們需要換一個溝通方式。", "我们需要换一个沟通方式。", "Wǒmen xūyào huàn yí ge gōutōng fāngshì.", "Work")
];
